Repository ABI-CTT-Group/digitaltwins-api, pull requests merged in 2023-09, with the labels that each got.

#51 Docs: Readme
  README.md
Labels: documentation

#54 Fix bug & add example for uploading dataset
  configs/templates/config.ini
  dtp/core/uploader.py
  dtp/gen3/metadata_convertor.py
  dtp/irods/irods.py
  examples/upload_dataset.py
Labels: enhancement

#56 Update Downloader class
  dtp/core/downloader.py
  dtp/irods/irods.py
  examples/download_dataset.py
  examples/irods/download_data.py
  examples/workflow/scripts/pretend_import.py
Labels: enhancement

#58 Update README.md
  README.md
Labels: bug

#59 update tutorials
  tutorials/tutorial_1_getting_started.ipynb
  tutorials/tutorial_2_create_datasets_and_description.ipynb
  tutorials/tutorial_2_create_datasets_and_its metadata.ipynb
  tutorials/tutorial_3_submit_datasets.ipynb
  tutorials/tutorial_3_upload_datasets.ipynb
  tutorials/tutorial_5_query_existing_datasets.ipynb
  tutorials/tutorial_6_download_existing_datasets.ipynb
Labels: documentation

#72 Add Deleter class
  digitaltwins/__init__.py
  digitaltwins/core/deleter.py
  digitaltwins/core/uploader.py
  digitaltwins/gen3/metadata_querier.py
  digitaltwins/irods/irods.py
  setup.py
Labels: enhancement

#74 Update the Querier
  digitaltwins/__init__.py
  digitaltwins/core/dataset.py
  digitaltwins/core/deleter.py
  digitaltwins/core/uploader.py
  digitaltwins/gen3/metadata_querier.py
  digitaltwins/gen3/metadata_uploader.py
  examples/delete_dataset.py
  examples/download_dataset.py
  examples/query_metadata.py
Labels: enhancement

#92 Updating gitignore to ignore PyCharm project xml files and updating survey link
  .gitignore
  tutorials/tutorial_1_getting_started.md
  tutorials/tutorial_2_exploring_and_downloading_platform_datasets.ipynb
  tutorials/tutorial_3_loading_and_exploring_sds_datasets.ipynb
  tutorials/tutorial_4_creating_sds_datasets.ipynb
  tutorials/tutorial_5_uploading_datasets.ipynb
  tutorials/workshop_1_describing_and_storing_data.md
Labels: documentation
